spring.datasource.url=jdbc:postgresql://localhost:5432/cti_insights
spring.datasource.username=postgres
spring.datasource.password=Senai2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true